// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m8s.proto

/*
Package m8s is a generated protocol buffer package.

It is generated from these files:
	m8s.proto

It has these top-level messages:
	Credentials
	CreateRequest
	Metadata
	BasicAuth
	GitCheckout
	Compose
	ComposeService
	Resource
	CreateResponse
	ExecRequest
	ExecResponse
	DescribeRequest
	DescribeResponse
	ListRequest
	ListResponse
	SSH
	SSHSetRequest
	SSHSetResponse
	SSHGetRequest
	SSHGetResponse
	DockerCfgRequest
	DockerCfgResponse
*/
package m8s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Credentials is used for authenicating with the PR service.
type Credentials struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Credentials) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// BuildRequest is used for submitting a new build.
type CreateRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Metadata    *Metadata    `protobuf:"bytes,2,opt,name=Metadata" json:"Metadata,omitempty"`
	Compose     *Compose     `protobuf:"bytes,3,opt,name=Compose" json:"Compose,omitempty"`
	GitCheckout *GitCheckout `protobuf:"bytes,4,opt,name=GitCheckout" json:"GitCheckout,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *CreateRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreateRequest) GetCompose() *Compose {
	if m != nil {
		return m.Compose
	}
	return nil
}

func (m *CreateRequest) GetGitCheckout() *GitCheckout {
	if m != nil {
		return m.GitCheckout
	}
	return nil
}

// Metadata is high level information about the build.
type Metadata struct {
	Name      string     `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Domains   []string   `protobuf:"bytes,3,rep,name=Domains" json:"Domains,omitempty"`
	BasicAuth *BasicAuth `protobuf:"bytes,4,opt,name=BasicAuth" json:"BasicAuth,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Metadata) GetBasicAuth() *BasicAuth {
	if m != nil {
		return m.BasicAuth
	}
	return nil
}

type BasicAuth struct {
	User string `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=Pass" json:"Pass,omitempty"`
}

func (m *BasicAuth) Reset()                    { *m = BasicAuth{} }
func (m *BasicAuth) String() string            { return proto.CompactTextString(m) }
func (*BasicAuth) ProtoMessage()               {}
func (*BasicAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BasicAuth) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BasicAuth) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

// GitCheckout is the details required to checkout the codebase.
type GitCheckout struct {
	// The repository we are cloning:
	// * https://github.com/owner/repo.git
	// * https://<token>:x-oauth-basic@github.com/owner/repo.git
	Repository string `protobuf:"bytes,1,opt,name=Repository" json:"Repository,omitempty"`
	Revision   string `protobuf:"bytes,2,opt,name=Revision" json:"Revision,omitempty"`
}

func (m *GitCheckout) Reset()                    { *m = GitCheckout{} }
func (m *GitCheckout) String() string            { return proto.CompactTextString(m) }
func (*GitCheckout) ProtoMessage()               {}
func (*GitCheckout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GitCheckout) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *GitCheckout) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

// Compose is our environment data, marshalled from a docker compose file.
type Compose struct {
	Services []*ComposeService `protobuf:"bytes,1,rep,name=Services" json:"Services,omitempty"`
}

func (m *Compose) Reset()                    { *m = Compose{} }
func (m *Compose) String() string            { return proto.CompactTextString(m) }
func (*Compose) ProtoMessage()               {}
func (*Compose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Compose) GetServices() []*ComposeService {
	if m != nil {
		return m.Services
	}
	return nil
}

// ComposeService is a container defintion, which we will use to build a pod.
type ComposeService struct {
	Name         string    `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Image        string    `protobuf:"bytes,2,opt,name=Image" json:"Image,omitempty"`
	Limits       *Resource `protobuf:"bytes,3,opt,name=Limits" json:"Limits,omitempty"`
	Reservations *Resource `protobuf:"bytes,4,opt,name=Reservations" json:"Reservations,omitempty"`
	Volumes      []string  `protobuf:"bytes,5,rep,name=Volumes" json:"Volumes,omitempty"`
	Ports        []string  `protobuf:"bytes,6,rep,name=Ports" json:"Ports,omitempty"`
	Environment  []string  `protobuf:"bytes,7,rep,name=Environment" json:"Environment,omitempty"`
	Tmpfs        []string  `protobuf:"bytes,8,rep,name=Tmpfs" json:"Tmpfs,omitempty"`
}

func (m *ComposeService) Reset()                    { *m = ComposeService{} }
func (m *ComposeService) String() string            { return proto.CompactTextString(m) }
func (*ComposeService) ProtoMessage()               {}
func (*ComposeService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ComposeService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComposeService) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ComposeService) GetLimits() *Resource {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *ComposeService) GetReservations() *Resource {
	if m != nil {
		return m.Reservations
	}
	return nil
}

func (m *ComposeService) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ComposeService) GetPorts() []string {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ComposeService) GetEnvironment() []string {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *ComposeService) GetTmpfs() []string {
	if m != nil {
		return m.Tmpfs
	}
	return nil
}

// Resource is used for setting CPU and Memory of the build.
type Resource struct {
	CPU    string `protobuf:"bytes,1,opt,name=CPU" json:"CPU,omitempty"`
	Memory string `protobuf:"bytes,2,opt,name=Memory" json:"Memory,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Resource) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *Resource) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

// BuildResponse is a streamed response used for printing build output and status.
type CreateResponse struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// ExecRequest is our command being send to the remote environment.
type ExecRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Container   string       `protobuf:"bytes,3,opt,name=Container" json:"Container,omitempty"`
	Command     string       `protobuf:"bytes,4,opt,name=Command" json:"Command,omitempty"`
}

func (m *ExecRequest) Reset()                    { *m = ExecRequest{} }
func (m *ExecRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()               {}
func (*ExecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ExecRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *ExecRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExecRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *ExecRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

// ExecResponse is a streamed response used to return output from the commands on the remove environment.
type ExecResponse struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *ExecResponse) Reset()                    { *m = ExecResponse{} }
func (m *ExecResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()               {}
func (*ExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ExecResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// DescribeRequest asks for an Environment which has already been deployed.
type DescribeRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DescribeRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *DescribeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// DescribeResponse responds with an Environment.
type DescribeResponse struct {
	Namespace  string   `protobuf:"bytes,1,opt,name=Namespace" json:"Namespace,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Domains    []string `protobuf:"bytes,3,rep,name=Domains" json:"Domains,omitempty"`
	Containers []string `protobuf:"bytes,4,rep,name=Containers" json:"Containers,omitempty"`
	SSH        []string `protobuf:"bytes,5,rep,name=SSH" json:"SSH,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DescribeResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DescribeResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DescribeResponse) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *DescribeResponse) GetContainers() []string {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *DescribeResponse) GetSSH() []string {
	if m != nil {
		return m.SSH
	}
	return nil
}

// DescribeRequest asks for all the Environments.
type ListRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

// ListResponse returns a list of Environments.
type ListResponse struct {
	Environments []string `protobuf:"bytes,1,rep,name=Environments" json:"Environments,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ListResponse) GetEnvironments() []string {
	if m != nil {
		return m.Environments
	}
	return nil
}

// SSH containers secrets for performing SSH commands on private endpoints.
type SSH struct {
	KnownHosts []byte `protobuf:"bytes,1,opt,name=KnownHosts,proto3" json:"KnownHosts,omitempty"`
	PrivateKey []byte `protobuf:"bytes,2,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
}

func (m *SSH) Reset()                    { *m = SSH{} }
func (m *SSH) String() string            { return proto.CompactTextString(m) }
func (*SSH) ProtoMessage()               {}
func (*SSH) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SSH) GetKnownHosts() []byte {
	if m != nil {
		return m.KnownHosts
	}
	return nil
}

func (m *SSH) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

// SetSSHRequest allows for the developer to set SSH secrets "out of band".
type SSHSetRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	SSH         *SSH         `protobuf:"bytes,2,opt,name=SSH" json:"SSH,omitempty"`
}

func (m *SSHSetRequest) Reset()                    { *m = SSHSetRequest{} }
func (m *SSHSetRequest) String() string            { return proto.CompactTextString(m) }
func (*SSHSetRequest) ProtoMessage()               {}
func (*SSHSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SSHSetRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *SSHSetRequest) GetSSH() *SSH {
	if m != nil {
		return m.SSH
	}
	return nil
}

// SetSSHResponse is a response after setting SSH.
type SSHSetResponse struct {
}

func (m *SSHSetResponse) Reset()                    { *m = SSHSetResponse{} }
func (m *SSHSetResponse) String() string            { return proto.CompactTextString(m) }
func (*SSHSetResponse) ProtoMessage()               {}
func (*SSHSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// SSHGetRequest request for the SSH configuration.
type SSHGetRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *SSHGetRequest) Reset()                    { *m = SSHGetRequest{} }
func (m *SSHGetRequest) String() string            { return proto.CompactTextString(m) }
func (*SSHGetRequest) ProtoMessage()               {}
func (*SSHGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SSHGetRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

// SSHGetResponse returns the SSH configuration.
type SSHGetResponse struct {
	SSH *SSH `protobuf:"bytes,1,opt,name=SSH" json:"SSH,omitempty"`
}

func (m *SSHGetResponse) Reset()                    { *m = SSHGetResponse{} }
func (m *SSHGetResponse) String() string            { return proto.CompactTextString(m) }
func (*SSHGetResponse) ProtoMessage()               {}
func (*SSHGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SSHGetResponse) GetSSH() *SSH {
	if m != nil {
		return m.SSH
	}
	return nil
}

// DockerCfgRequest requests the Docker configuration.
type DockerCfgRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *DockerCfgRequest) Reset()                    { *m = DockerCfgRequest{} }
func (m *DockerCfgRequest) String() string            { return proto.CompactTextString(m) }
func (*DockerCfgRequest) ProtoMessage()               {}
func (*DockerCfgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DockerCfgRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

// DockerCfgResponse returns the Docker configuration.
type DockerCfgResponse struct {
	Registry string `protobuf:"bytes,1,opt,name=Registry" json:"Registry,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Auth     string `protobuf:"bytes,5,opt,name=Auth" json:"Auth,omitempty"`
}

func (m *DockerCfgResponse) Reset()                    { *m = DockerCfgResponse{} }
func (m *DockerCfgResponse) String() string            { return proto.CompactTextString(m) }
func (*DockerCfgResponse) ProtoMessage()               {}
func (*DockerCfgResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *DockerCfgResponse) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *DockerCfgResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DockerCfgResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DockerCfgResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DockerCfgResponse) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func init() {
	proto.RegisterType((*Credentials)(nil), "m8s.Credentials")
	proto.RegisterType((*CreateRequest)(nil), "m8s.CreateRequest")
	proto.RegisterType((*Metadata)(nil), "m8s.Metadata")
	proto.RegisterType((*BasicAuth)(nil), "m8s.BasicAuth")
	proto.RegisterType((*GitCheckout)(nil), "m8s.GitCheckout")
	proto.RegisterType((*Compose)(nil), "m8s.Compose")
	proto.RegisterType((*ComposeService)(nil), "m8s.ComposeService")
	proto.RegisterType((*Resource)(nil), "m8s.Resource")
	proto.RegisterType((*CreateResponse)(nil), "m8s.CreateResponse")
	proto.RegisterType((*ExecRequest)(nil), "m8s.ExecRequest")
	proto.RegisterType((*ExecResponse)(nil), "m8s.ExecResponse")
	proto.RegisterType((*DescribeRequest)(nil), "m8s.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "m8s.DescribeResponse")
	proto.RegisterType((*ListRequest)(nil), "m8s.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "m8s.ListResponse")
	proto.RegisterType((*SSH)(nil), "m8s.SSH")
	proto.RegisterType((*SSHSetRequest)(nil), "m8s.SSHSetRequest")
	proto.RegisterType((*SSHSetResponse)(nil), "m8s.SSHSetResponse")
	proto.RegisterType((*SSHGetRequest)(nil), "m8s.SSHGetRequest")
	proto.RegisterType((*SSHGetResponse)(nil), "m8s.SSHGetResponse")
	proto.RegisterType((*DockerCfgRequest)(nil), "m8s.DockerCfgRequest")
	proto.RegisterType((*DockerCfgResponse)(nil), "m8s.DockerCfgResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for M8S service

type M8SClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (M8S_CreateClient, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (M8S_ExecClient, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Used for getting Docker registry secrets.
	DockerCfg(ctx context.Context, in *DockerCfgRequest, opts ...grpc.CallOption) (*DockerCfgResponse, error)
}

type m8SClient struct {
	cc *grpc.ClientConn
}

func NewM8SClient(cc *grpc.ClientConn) M8SClient {
	return &m8SClient{cc}
}

func (c *m8SClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (M8S_CreateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_M8S_serviceDesc.Streams[0], c.cc, "/m8s.m8s/Create", opts...)
	if err != nil {
		return nil, err
	}
	x := &m8SCreateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type M8S_CreateClient interface {
	Recv() (*CreateResponse, error)
	grpc.ClientStream
}

type m8SCreateClient struct {
	grpc.ClientStream
}

func (x *m8SCreateClient) Recv() (*CreateResponse, error) {
	m := new(CreateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *m8SClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (M8S_ExecClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_M8S_serviceDesc.Streams[1], c.cc, "/m8s.m8s/Exec", opts...)
	if err != nil {
		return nil, err
	}
	x := &m8SExecClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type M8S_ExecClient interface {
	Recv() (*ExecResponse, error)
	grpc.ClientStream
}

type m8SExecClient struct {
	grpc.ClientStream
}

func (x *m8SExecClient) Recv() (*ExecResponse, error) {
	m := new(ExecResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *m8SClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/m8s.m8s/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m8SClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/m8s.m8s/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *m8SClient) DockerCfg(ctx context.Context, in *DockerCfgRequest, opts ...grpc.CallOption) (*DockerCfgResponse, error) {
	out := new(DockerCfgResponse)
	err := grpc.Invoke(ctx, "/m8s.m8s/DockerCfg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for M8S service

type M8SServer interface {
	Create(*CreateRequest, M8S_CreateServer) error
	Exec(*ExecRequest, M8S_ExecServer) error
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Used for getting Docker registry secrets.
	DockerCfg(context.Context, *DockerCfgRequest) (*DockerCfgResponse, error)
}

func RegisterM8SServer(s *grpc.Server, srv M8SServer) {
	s.RegisterService(&_M8S_serviceDesc, srv)
}

func _M8S_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(M8SServer).Create(m, &m8SCreateServer{stream})
}

type M8S_CreateServer interface {
	Send(*CreateResponse) error
	grpc.ServerStream
}

type m8SCreateServer struct {
	grpc.ServerStream
}

func (x *m8SCreateServer) Send(m *CreateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _M8S_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(M8SServer).Exec(m, &m8SExecServer{stream})
}

type M8S_ExecServer interface {
	Send(*ExecResponse) error
	grpc.ServerStream
}

type m8SExecServer struct {
	grpc.ServerStream
}

func (x *m8SExecServer) Send(m *ExecResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _M8S_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M8SServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m8s.m8s/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M8SServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M8S_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M8SServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m8s.m8s/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M8SServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _M8S_DockerCfg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerCfgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M8SServer).DockerCfg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m8s.m8s/DockerCfg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M8SServer).DockerCfg(ctx, req.(*DockerCfgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M8S_serviceDesc = grpc.ServiceDesc{
	ServiceName: "m8s.m8s",
	HandlerType: (*M8SServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _M8S_Describe_Handler,
		},
		{
			MethodName: "List",
			Handler:    _M8S_List_Handler,
		},
		{
			MethodName: "DockerCfg",
			Handler:    _M8S_DockerCfg_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Create",
			Handler:       _M8S_Create_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _M8S_Exec_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "m8s.proto",
}

func init() { proto.RegisterFile("m8s.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0xd6, 0x89, 0xe3, 0x3d, 0x76, 0x82, 0x3b, 0x0d, 0xd5, 0xca, 0xaa, 0xaa, 0x68, 0x10,
	0xc8, 0xa0, 0xd2, 0x82, 0x0b, 0x52, 0x41, 0xdc, 0x94, 0x8d, 0x89, 0xab, 0x36, 0xc8, 0x9a, 0xa5,
	0x48, 0x5c, 0xa1, 0xe9, 0xfa, 0x24, 0x1d, 0x25, 0xbb, 0x63, 0x76, 0xc6, 0x2e, 0x3c, 0x04, 0x12,
	0x5c, 0xf0, 0x52, 0x3c, 0x13, 0x17, 0x68, 0x7e, 0x76, 0x77, 0x6c, 0x45, 0x42, 0xc8, 0xbd, 0x9b,
	0xf3, 0x9d, 0xbf, 0x6f, 0xce, 0xcf, 0xec, 0x42, 0x5c, 0x3c, 0x55, 0x8f, 0x96, 0x95, 0xd4, 0x92,
	0x74, 0x8a, 0xa7, 0x8a, 0x7e, 0x00, 0xfd, 0xb4, 0xc2, 0x05, 0x96, 0x5a, 0xf0, 0x6b, 0x45, 0x8e,
	0x61, 0xff, 0x07, 0x79, 0x85, 0x65, 0x12, 0x9d, 0x44, 0xe3, 0x98, 0x39, 0x81, 0xfe, 0x1d, 0xc1,
	0x61, 0x5a, 0x21, 0xd7, 0xc8, 0xf0, 0x97, 0x15, 0x2a, 0x4d, 0x26, 0x1b, 0x6e, 0xd6, 0xba, 0x3f,
	0x19, 0x3e, 0x32, 0xc1, 0x03, 0x9c, 0x6d, 0xc4, 0xfe, 0x18, 0x7a, 0xe7, 0xa8, 0xf9, 0x82, 0x6b,
	0x9e, 0xdc, 0xb6, 0x0e, 0x87, 0xd6, 0xa1, 0x06, 0x59, 0xa3, 0x26, 0x1f, 0xc1, 0x41, 0x2a, 0x8b,
	0xa5, 0x54, 0x98, 0x74, 0xac, 0xe5, 0xc0, 0x85, 0x76, 0x18, 0xab, 0x95, 0x86, 0xc6, 0x99, 0xd0,
	0xe9, 0x1b, 0xcc, 0xaf, 0xe4, 0x4a, 0x27, 0x7b, 0x01, 0x8d, 0x00, 0x67, 0xa1, 0x11, 0xbd, 0x68,
	0x69, 0x10, 0x02, 0x7b, 0xdf, 0xf3, 0x02, 0x2d, 0x9d, 0x98, 0xd9, 0x33, 0x49, 0xe0, 0xe0, 0x54,
	0x16, 0x5c, 0x94, 0x2a, 0xe9, 0x9c, 0x74, 0xc6, 0x31, 0xab, 0x45, 0xf2, 0x10, 0xe2, 0x6f, 0xb9,
	0x12, 0xf9, 0xb3, 0x95, 0x7e, 0xe3, 0x73, 0x1d, 0xd9, 0x5c, 0x0d, 0xca, 0x5a, 0x03, 0xfa, 0x24,
	0xb0, 0x36, 0x89, 0x5e, 0x29, 0xac, 0x7c, 0x59, 0xed, 0xd9, 0x60, 0x73, 0xae, 0x54, 0x9d, 0xdc,
	0x9c, 0xe9, 0xf3, 0x8d, 0x0b, 0x91, 0x07, 0x00, 0x0c, 0x97, 0x52, 0x09, 0x2d, 0xab, 0xdf, 0xbc,
	0x73, 0x80, 0x90, 0x11, 0xf4, 0x18, 0xae, 0x85, 0x12, 0xb2, 0xf4, 0x61, 0x1a, 0x99, 0x7e, 0xdd,
	0xd4, 0x90, 0x3c, 0x86, 0x5e, 0x86, 0xd5, 0x5a, 0xe4, 0x68, 0x5a, 0xd5, 0x19, 0xf7, 0x27, 0x77,
	0xc3, 0x7a, 0x7a, 0x1d, 0x6b, 0x8c, 0xe8, 0x3f, 0x11, 0x1c, 0x6d, 0x2a, 0x9b, 0x52, 0x45, 0x41,
	0xa9, 0x8e, 0x61, 0xff, 0x79, 0xc1, 0x2f, 0xeb, 0xfa, 0x39, 0x81, 0x7c, 0x08, 0xdd, 0x97, 0xa2,
	0x10, 0x5a, 0xf9, 0xde, 0xb9, 0x2e, 0x33, 0x54, 0x72, 0x55, 0xe5, 0xc8, 0xbc, 0x92, 0x7c, 0x0e,
	0x03, 0x86, 0x0a, 0xab, 0x35, 0xd7, 0x42, 0x96, 0xca, 0x17, 0x74, 0xcb, 0x78, 0xc3, 0xc4, 0xb4,
	0xe6, 0x47, 0x79, 0xbd, 0x2a, 0x50, 0x25, 0xfb, 0xae, 0x35, 0x5e, 0x34, 0x4c, 0xe6, 0xb2, 0xd2,
	0x2a, 0xe9, 0x5a, 0xdc, 0x09, 0xe4, 0x04, 0xfa, 0xd3, 0x72, 0x2d, 0x2a, 0x59, 0x16, 0x58, 0xea,
	0xe4, 0xc0, 0xea, 0x42, 0xc8, 0xce, 0x7b, 0xb1, 0xbc, 0x50, 0x49, 0xcf, 0xf9, 0x59, 0x81, 0x7e,
	0x61, 0xca, 0xea, 0x18, 0x90, 0x21, 0x74, 0xd2, 0xf9, 0x2b, 0x7f, 0x6d, 0x73, 0x24, 0xf7, 0xa0,
	0x7b, 0x8e, 0x85, 0x69, 0x88, 0xbb, 0xb6, 0x97, 0xe8, 0x27, 0x70, 0x54, 0x2f, 0x89, 0x5a, 0xca,
	0x52, 0xd9, 0x51, 0x3a, 0x47, 0xa5, 0x4c, 0x85, 0x9c, 0x7f, 0x2d, 0xd2, 0xdf, 0x23, 0xe8, 0x4f,
	0x7f, 0xc5, 0x7c, 0x97, 0x7d, 0xba, 0x69, 0x78, 0xef, 0x43, 0x9c, 0xca, 0x52, 0x73, 0x51, 0x62,
	0x65, 0xcb, 0x1f, 0xb3, 0x16, 0x30, 0x7c, 0x52, 0x59, 0x14, 0xbc, 0x5c, 0xd8, 0x6a, 0xc7, 0xac,
	0x16, 0xe9, 0x18, 0x06, 0x8e, 0xce, 0x7f, 0x32, 0xff, 0x09, 0xde, 0x3b, 0x45, 0x95, 0x57, 0xe2,
	0x35, 0xbe, 0x63, 0xf2, 0xf4, 0x8f, 0x08, 0x86, 0x6d, 0x6c, 0xcf, 0xe4, 0x3e, 0xc4, 0x46, 0xa9,
	0x96, 0x3c, 0xaf, 0xb9, 0xb4, 0xc0, 0xff, 0x5c, 0xe0, 0x07, 0x00, 0x4d, 0x31, 0xcc, 0xc0, 0x19,
	0x65, 0x80, 0x98, 0x5e, 0x67, 0xd9, 0xcc, 0xcf, 0x96, 0x39, 0xd2, 0x67, 0xd0, 0x7f, 0x29, 0x94,
	0xde, 0xe1, 0xa6, 0x74, 0x02, 0x03, 0x17, 0xc2, 0x5f, 0x88, 0xc2, 0x20, 0x98, 0x40, 0xb7, 0x90,
	0x31, 0xdb, 0xc0, 0xe8, 0xd4, 0x12, 0x31, 0x7c, 0x5f, 0x94, 0xf2, 0x6d, 0x39, 0x93, 0x4a, 0xbb,
	0x6c, 0x03, 0x16, 0x20, 0x46, 0x3f, 0xaf, 0xc4, 0x9a, 0x6b, 0x7c, 0x81, 0x6e, 0x1a, 0x07, 0x2c,
	0x40, 0xe8, 0xcf, 0x70, 0x98, 0x65, 0xb3, 0x0c, 0x77, 0xe1, 0x4f, 0x46, 0xae, 0x28, 0xee, 0xc5,
	0xee, 0x59, 0xdb, 0x2c, 0x9b, 0xb9, 0xf2, 0x0c, 0xe1, 0xa8, 0x4e, 0xe0, 0x6e, 0x47, 0x53, 0x9b,
	0xf2, 0x6c, 0xa7, 0x94, 0xf4, 0xa1, 0x0d, 0x7b, 0xd6, 0x86, 0xad, 0x49, 0x44, 0x37, 0x91, 0xf8,
	0x0e, 0x86, 0xa7, 0x32, 0xbf, 0xc2, 0x2a, 0xbd, 0xb8, 0xdc, 0x25, 0xeb, 0x9f, 0x11, 0xdc, 0x09,
	0x02, 0x35, 0x99, 0x7b, 0x0c, 0x2f, 0x85, 0xd2, 0xcd, 0x03, 0xdc, 0xc8, 0x46, 0x67, 0x5e, 0xf2,
	0xb2, 0x9d, 0xc0, 0x46, 0x36, 0x3a, 0xf3, 0xa2, 0xbf, 0x95, 0xd5, 0xc2, 0x2f, 0x62, 0x23, 0x9b,
	0x57, 0x67, 0x5a, 0x70, 0x71, 0xed, 0xb7, 0xd0, 0x09, 0x66, 0x96, 0xed, 0x97, 0x65, 0xdf, 0xcd,
	0xb2, 0x39, 0x4f, 0xfe, 0xba, 0x0d, 0xe6, 0x33, 0x4d, 0xbe, 0x84, 0xae, 0x7b, 0x5b, 0x08, 0xa9,
	0x2f, 0xd1, 0x7e, 0x8d, 0x47, 0x77, 0x37, 0x30, 0xdf, 0x89, 0x5b, 0x9f, 0x45, 0xe4, 0x31, 0xec,
	0x99, 0xb5, 0x26, 0xee, 0xe6, 0xc1, 0x83, 0x33, 0xba, 0x13, 0x20, 0x81, 0xc3, 0x57, 0xd0, 0xab,
	0x37, 0x90, 0x1c, 0x5b, 0x93, 0xad, 0x65, 0x1f, 0xbd, 0xbf, 0x85, 0xd6, 0xce, 0xe4, 0x53, 0xd8,
	0x33, 0x73, 0xee, 0x73, 0x05, 0x5b, 0xe3, 0x73, 0x85, 0x4b, 0x40, 0x6f, 0x91, 0x6f, 0x20, 0x6e,
	0x8a, 0x4d, 0x7c, 0xd0, 0xad, 0x2e, 0x8e, 0xee, 0x6d, 0xc3, 0xb5, 0xf7, 0xeb, 0xae, 0xfd, 0x85,
	0x79, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x3e, 0xb0, 0xb0, 0xcf, 0x08, 0x00, 0x00,
}
