version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:30"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 10
