// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pr.proto

/*
Package pr is a generated protocol buffer package.

It is generated from these files:
	pr.proto

It has these top-level messages:
	Credentials
	BuildRequest
	Metadata
	GitCheckout
	Compose
	ComposeService
	Exec
	BuildResponse
	Container
	Environment
	DescribeRequest
	DescribeResponse
	ListRequest
	ListResponse
	SSH
	SSHSetRequest
	SSHSetResponse
	SSHGetRequest
	SSHGetResponse
	DockerCfg
	DockerCfgSetRequest
	DockerCfgSetResponse
	DockerCfgGetRequest
	DockerCfgGetResponse
*/
package pr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Credentials is used for authenicating with the PR service.
type Credentials struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Credentials) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// BuildRequest is used for submitting a new build.
type BuildRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Metadata    *Metadata    `protobuf:"bytes,2,opt,name=Metadata" json:"Metadata,omitempty"`
	Compose     *Compose     `protobuf:"bytes,3,opt,name=Compose" json:"Compose,omitempty"`
	GitCheckout *GitCheckout `protobuf:"bytes,4,opt,name=GitCheckout" json:"GitCheckout,omitempty"`
	Exec        *Exec        `protobuf:"bytes,5,opt,name=Exec" json:"Exec,omitempty"`
	Keep        string       `protobuf:"bytes,6,opt,name=Keep" json:"Keep,omitempty"`
}

func (m *BuildRequest) Reset()                    { *m = BuildRequest{} }
func (m *BuildRequest) String() string            { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()               {}
func (*BuildRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BuildRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *BuildRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *BuildRequest) GetCompose() *Compose {
	if m != nil {
		return m.Compose
	}
	return nil
}

func (m *BuildRequest) GetGitCheckout() *GitCheckout {
	if m != nil {
		return m.GitCheckout
	}
	return nil
}

func (m *BuildRequest) GetExec() *Exec {
	if m != nil {
		return m.Exec
	}
	return nil
}

func (m *BuildRequest) GetKeep() string {
	if m != nil {
		return m.Keep
	}
	return ""
}

// Metadata is high level information about the build.
type Metadata struct {
	Name    string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Domains []string `protobuf:"bytes,3,rep,name=Domains" json:"Domains,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

// GitCheckout is the details required to checkout the codebase.
type GitCheckout struct {
	// The repository we are cloning:
	// * https://github.com/owner/repo.git
	// * https://<token>:x-oauth-basic@github.com/owner/repo.git
	Repository string `protobuf:"bytes,1,opt,name=Repository" json:"Repository,omitempty"`
	Revision   string `protobuf:"bytes,2,opt,name=Revision" json:"Revision,omitempty"`
}

func (m *GitCheckout) Reset()                    { *m = GitCheckout{} }
func (m *GitCheckout) String() string            { return proto.CompactTextString(m) }
func (*GitCheckout) ProtoMessage()               {}
func (*GitCheckout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GitCheckout) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *GitCheckout) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

// Compose is our environment data, marshalled from a docker compose file.
type Compose struct {
	Services []*ComposeService `protobuf:"bytes,1,rep,name=Services" json:"Services,omitempty"`
}

func (m *Compose) Reset()                    { *m = Compose{} }
func (m *Compose) String() string            { return proto.CompactTextString(m) }
func (*Compose) ProtoMessage()               {}
func (*Compose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Compose) GetServices() []*ComposeService {
	if m != nil {
		return m.Services
	}
	return nil
}

// ComposeService is a container defintion, which we will use to build a pod.
type ComposeService struct {
	Name        string   `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Image       string   `protobuf:"bytes,2,opt,name=Image" json:"Image,omitempty"`
	Volumes     []string `protobuf:"bytes,3,rep,name=Volumes" json:"Volumes,omitempty"`
	Ports       []string `protobuf:"bytes,4,rep,name=Ports" json:"Ports,omitempty"`
	Environment []string `protobuf:"bytes,5,rep,name=Environment" json:"Environment,omitempty"`
}

func (m *ComposeService) Reset()                    { *m = ComposeService{} }
func (m *ComposeService) String() string            { return proto.CompactTextString(m) }
func (*ComposeService) ProtoMessage()               {}
func (*ComposeService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ComposeService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComposeService) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ComposeService) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ComposeService) GetPorts() []string {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ComposeService) GetEnvironment() []string {
	if m != nil {
		return m.Environment
	}
	return nil
}

// Exec has the steps we require to build an environment and in which container.
type Exec struct {
	Container string   `protobuf:"bytes,1,opt,name=Container" json:"Container,omitempty"`
	Steps     []string `protobuf:"bytes,5,rep,name=Steps" json:"Steps,omitempty"`
}

func (m *Exec) Reset()                    { *m = Exec{} }
func (m *Exec) String() string            { return proto.CompactTextString(m) }
func (*Exec) ProtoMessage()               {}
func (*Exec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Exec) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *Exec) GetSteps() []string {
	if m != nil {
		return m.Steps
	}
	return nil
}

// BuildResponse is a streamed response used for printing build output and status.
type BuildResponse struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *BuildResponse) Reset()                    { *m = BuildResponse{} }
func (m *BuildResponse) String() string            { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()               {}
func (*BuildResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BuildResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Container shows a container which is deployed in an Environment.
type Container struct {
	Name  string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=Image" json:"Image,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

// Environment shows a group of containers which have been deployed.
type Environment struct {
	Namespace  string       `protobuf:"bytes,1,opt,name=Namespace" json:"Namespace,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Domains    []string     `protobuf:"bytes,3,rep,name=Domains" json:"Domains,omitempty"`
	Containers []*Container `protobuf:"bytes,4,rep,name=Containers" json:"Containers,omitempty"`
}

func (m *Environment) Reset()                    { *m = Environment{} }
func (m *Environment) String() string            { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()               {}
func (*Environment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Environment) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Environment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

// DescribeRequest asks for an Environment which has already been deployed.
type DescribeRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DescribeRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *DescribeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// DescribeResponse responds with an Environment.
type DescribeResponse struct {
	Environment *Environment `protobuf:"bytes,1,opt,name=Environment" json:"Environment,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DescribeResponse) GetEnvironment() *Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

// DescribeRequest asks for all the Environments.
type ListRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

// ListResponse returns a list of Environments.
type ListResponse struct {
	Environments []*Environment `protobuf:"bytes,1,rep,name=Environments" json:"Environments,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListResponse) GetEnvironments() []*Environment {
	if m != nil {
		return m.Environments
	}
	return nil
}

// SSH containers secrets for performing SSH commands on private endpoints.
type SSH struct {
	KnownHosts []byte `protobuf:"bytes,1,opt,name=KnownHosts,proto3" json:"KnownHosts,omitempty"`
	PrivateKey []byte `protobuf:"bytes,2,opt,name=PrivateKey,proto3" json:"PrivateKey,omitempty"`
}

func (m *SSH) Reset()                    { *m = SSH{} }
func (m *SSH) String() string            { return proto.CompactTextString(m) }
func (*SSH) ProtoMessage()               {}
func (*SSH) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SSH) GetKnownHosts() []byte {
	if m != nil {
		return m.KnownHosts
	}
	return nil
}

func (m *SSH) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

// SetSSHRequest allows for the developer to set SSH secrets "out of band".
type SSHSetRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	SSH         *SSH         `protobuf:"bytes,2,opt,name=SSH" json:"SSH,omitempty"`
}

func (m *SSHSetRequest) Reset()                    { *m = SSHSetRequest{} }
func (m *SSHSetRequest) String() string            { return proto.CompactTextString(m) }
func (*SSHSetRequest) ProtoMessage()               {}
func (*SSHSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SSHSetRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *SSHSetRequest) GetSSH() *SSH {
	if m != nil {
		return m.SSH
	}
	return nil
}

// SetSSHResponse is a response after setting SSH.
type SSHSetResponse struct {
}

func (m *SSHSetResponse) Reset()                    { *m = SSHSetResponse{} }
func (m *SSHSetResponse) String() string            { return proto.CompactTextString(m) }
func (*SSHSetResponse) ProtoMessage()               {}
func (*SSHSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

// SSHGetRequest request for the SSH configuration.
type SSHGetRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *SSHGetRequest) Reset()                    { *m = SSHGetRequest{} }
func (m *SSHGetRequest) String() string            { return proto.CompactTextString(m) }
func (*SSHGetRequest) ProtoMessage()               {}
func (*SSHGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SSHGetRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

// SSHGetResponse returns the SSH configuration.
type SSHGetResponse struct {
	SSH *SSH `protobuf:"bytes,1,opt,name=SSH" json:"SSH,omitempty"`
}

func (m *SSHGetResponse) Reset()                    { *m = SSHGetResponse{} }
func (m *SSHGetResponse) String() string            { return proto.CompactTextString(m) }
func (*SSHGetResponse) ProtoMessage()               {}
func (*SSHGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SSHGetResponse) GetSSH() *SSH {
	if m != nil {
		return m.SSH
	}
	return nil
}

// DockerCfg contains standard Docker configuration eg ~/.docker/config
type DockerCfg struct {
	Registry string `protobuf:"bytes,1,opt,name=Registry" json:"Registry,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Auth     string `protobuf:"bytes,5,opt,name=Auth" json:"Auth,omitempty"`
}

func (m *DockerCfg) Reset()                    { *m = DockerCfg{} }
func (m *DockerCfg) String() string            { return proto.CompactTextString(m) }
func (*DockerCfg) ProtoMessage()               {}
func (*DockerCfg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DockerCfg) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *DockerCfg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DockerCfg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DockerCfg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DockerCfg) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

// DockerCfgSetRequest is for setting new Docker configuration.
type DockerCfgSetRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	DockerCfg   *DockerCfg   `protobuf:"bytes,2,opt,name=DockerCfg" json:"DockerCfg,omitempty"`
}

func (m *DockerCfgSetRequest) Reset()                    { *m = DockerCfgSetRequest{} }
func (m *DockerCfgSetRequest) String() string            { return proto.CompactTextString(m) }
func (*DockerCfgSetRequest) ProtoMessage()               {}
func (*DockerCfgSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DockerCfgSetRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *DockerCfgSetRequest) GetDockerCfg() *DockerCfg {
	if m != nil {
		return m.DockerCfg
	}
	return nil
}

// DockerCfgSetResponse returns if setting the Docker configuration was a success.
type DockerCfgSetResponse struct {
}

func (m *DockerCfgSetResponse) Reset()                    { *m = DockerCfgSetResponse{} }
func (m *DockerCfgSetResponse) String() string            { return proto.CompactTextString(m) }
func (*DockerCfgSetResponse) ProtoMessage()               {}
func (*DockerCfgSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

// DockerCfgGetRequest requests the Docker configuration.
type DockerCfgGetRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *DockerCfgGetRequest) Reset()                    { *m = DockerCfgGetRequest{} }
func (m *DockerCfgGetRequest) String() string            { return proto.CompactTextString(m) }
func (*DockerCfgGetRequest) ProtoMessage()               {}
func (*DockerCfgGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DockerCfgGetRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

// DockerCfgGetResponse returns the Docker configuration.
type DockerCfgGetResponse struct {
	DockerCfg *DockerCfg `protobuf:"bytes,1,opt,name=DockerCfg" json:"DockerCfg,omitempty"`
}

func (m *DockerCfgGetResponse) Reset()                    { *m = DockerCfgGetResponse{} }
func (m *DockerCfgGetResponse) String() string            { return proto.CompactTextString(m) }
func (*DockerCfgGetResponse) ProtoMessage()               {}
func (*DockerCfgGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *DockerCfgGetResponse) GetDockerCfg() *DockerCfg {
	if m != nil {
		return m.DockerCfg
	}
	return nil
}

func init() {
	proto.RegisterType((*Credentials)(nil), "pr.Credentials")
	proto.RegisterType((*BuildRequest)(nil), "pr.BuildRequest")
	proto.RegisterType((*Metadata)(nil), "pr.Metadata")
	proto.RegisterType((*GitCheckout)(nil), "pr.GitCheckout")
	proto.RegisterType((*Compose)(nil), "pr.Compose")
	proto.RegisterType((*ComposeService)(nil), "pr.ComposeService")
	proto.RegisterType((*Exec)(nil), "pr.Exec")
	proto.RegisterType((*BuildResponse)(nil), "pr.BuildResponse")
	proto.RegisterType((*Container)(nil), "pr.Container")
	proto.RegisterType((*Environment)(nil), "pr.Environment")
	proto.RegisterType((*DescribeRequest)(nil), "pr.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "pr.DescribeResponse")
	proto.RegisterType((*ListRequest)(nil), "pr.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "pr.ListResponse")
	proto.RegisterType((*SSH)(nil), "pr.SSH")
	proto.RegisterType((*SSHSetRequest)(nil), "pr.SSHSetRequest")
	proto.RegisterType((*SSHSetResponse)(nil), "pr.SSHSetResponse")
	proto.RegisterType((*SSHGetRequest)(nil), "pr.SSHGetRequest")
	proto.RegisterType((*SSHGetResponse)(nil), "pr.SSHGetResponse")
	proto.RegisterType((*DockerCfg)(nil), "pr.DockerCfg")
	proto.RegisterType((*DockerCfgSetRequest)(nil), "pr.DockerCfgSetRequest")
	proto.RegisterType((*DockerCfgSetResponse)(nil), "pr.DockerCfgSetResponse")
	proto.RegisterType((*DockerCfgGetRequest)(nil), "pr.DockerCfgGetRequest")
	proto.RegisterType((*DockerCfgGetResponse)(nil), "pr.DockerCfgGetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PR service

type PRClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (PR_BuildClient, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Used for setting and getting SSH credentials.
	SSHSet(ctx context.Context, in *SSHSetRequest, opts ...grpc.CallOption) (*SSHSetResponse, error)
	SSHGet(ctx context.Context, in *SSHGetRequest, opts ...grpc.CallOption) (*SSHGetResponse, error)
	// Used for setting and getting Docker registry secrets.
	DockerCfgSet(ctx context.Context, in *DockerCfgSetRequest, opts ...grpc.CallOption) (*DockerCfgSetResponse, error)
	DockerCfgGet(ctx context.Context, in *DockerCfgGetRequest, opts ...grpc.CallOption) (*DockerCfgGetResponse, error)
}

type pRClient struct {
	cc *grpc.ClientConn
}

func NewPRClient(cc *grpc.ClientConn) PRClient {
	return &pRClient{cc}
}

func (c *pRClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (PR_BuildClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PR_serviceDesc.Streams[0], c.cc, "/pr.PR/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &pRBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PR_BuildClient interface {
	Recv() (*BuildResponse, error)
	grpc.ClientStream
}

type pRBuildClient struct {
	grpc.ClientStream
}

func (x *pRBuildClient) Recv() (*BuildResponse, error) {
	m := new(BuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pRClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/pr.PR/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pRClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/pr.PR/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pRClient) SSHSet(ctx context.Context, in *SSHSetRequest, opts ...grpc.CallOption) (*SSHSetResponse, error) {
	out := new(SSHSetResponse)
	err := grpc.Invoke(ctx, "/pr.PR/SSHSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pRClient) SSHGet(ctx context.Context, in *SSHGetRequest, opts ...grpc.CallOption) (*SSHGetResponse, error) {
	out := new(SSHGetResponse)
	err := grpc.Invoke(ctx, "/pr.PR/SSHGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pRClient) DockerCfgSet(ctx context.Context, in *DockerCfgSetRequest, opts ...grpc.CallOption) (*DockerCfgSetResponse, error) {
	out := new(DockerCfgSetResponse)
	err := grpc.Invoke(ctx, "/pr.PR/DockerCfgSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pRClient) DockerCfgGet(ctx context.Context, in *DockerCfgGetRequest, opts ...grpc.CallOption) (*DockerCfgGetResponse, error) {
	out := new(DockerCfgGetResponse)
	err := grpc.Invoke(ctx, "/pr.PR/DockerCfgGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PR service

type PRServer interface {
	Build(*BuildRequest, PR_BuildServer) error
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Used for setting and getting SSH credentials.
	SSHSet(context.Context, *SSHSetRequest) (*SSHSetResponse, error)
	SSHGet(context.Context, *SSHGetRequest) (*SSHGetResponse, error)
	// Used for setting and getting Docker registry secrets.
	DockerCfgSet(context.Context, *DockerCfgSetRequest) (*DockerCfgSetResponse, error)
	DockerCfgGet(context.Context, *DockerCfgGetRequest) (*DockerCfgGetResponse, error)
}

func RegisterPRServer(s *grpc.Server, srv PRServer) {
	s.RegisterService(&_PR_serviceDesc, srv)
}

func _PR_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PRServer).Build(m, &pRBuildServer{stream})
}

type PR_BuildServer interface {
	Send(*BuildResponse) error
	grpc.ServerStream
}

type pRBuildServer struct {
	grpc.ServerStream
}

func (x *pRBuildServer) Send(m *BuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PR_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PRServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pr.PR/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PRServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PR_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PRServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pr.PR/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PRServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PR_SSHSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PRServer).SSHSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pr.PR/SSHSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PRServer).SSHSet(ctx, req.(*SSHSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PR_SSHGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PRServer).SSHGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pr.PR/SSHGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PRServer).SSHGet(ctx, req.(*SSHGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PR_DockerCfgSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerCfgSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PRServer).DockerCfgSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pr.PR/DockerCfgSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PRServer).DockerCfgSet(ctx, req.(*DockerCfgSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PR_DockerCfgGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerCfgGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PRServer).DockerCfgGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pr.PR/DockerCfgGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PRServer).DockerCfgGet(ctx, req.(*DockerCfgGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PR_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pr.PR",
	HandlerType: (*PRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PR_Describe_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PR_List_Handler,
		},
		{
			MethodName: "SSHSet",
			Handler:    _PR_SSHSet_Handler,
		},
		{
			MethodName: "SSHGet",
			Handler:    _PR_SSHGet_Handler,
		},
		{
			MethodName: "DockerCfgSet",
			Handler:    _PR_DockerCfgSet_Handler,
		},
		{
			MethodName: "DockerCfgGet",
			Handler:    _PR_DockerCfgGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Build",
			Handler:       _PR_Build_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pr.proto",
}

func init() { proto.RegisterFile("pr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdf, 0x4f, 0x1b, 0x39,
	0x10, 0xbe, 0x25, 0x09, 0x64, 0x27, 0x01, 0x82, 0x89, 0xee, 0xf6, 0x22, 0x74, 0x42, 0x3e, 0x9d,
	0x94, 0x13, 0xba, 0x08, 0x82, 0x4e, 0x77, 0xed, 0x53, 0xcb, 0x12, 0x6d, 0x10, 0xa5, 0x8a, 0xbc,
	0x6d, 0xd5, 0x97, 0x3e, 0x2c, 0x89, 0x0b, 0x2b, 0x92, 0xf5, 0x76, 0xed, 0x84, 0xf2, 0x1f, 0xb4,
	0x12, 0xff, 0x6f, 0x5f, 0x2b, 0x7b, 0x7f, 0xd9, 0x0d, 0xad, 0xda, 0xe6, 0x6d, 0xe7, 0x9b, 0xf1,
	0x37, 0xdf, 0xcc, 0xd8, 0x93, 0x40, 0x3d, 0x4e, 0x7a, 0x71, 0xc2, 0x04, 0x43, 0x6b, 0x71, 0x82,
	0xff, 0x84, 0x86, 0x9b, 0xd0, 0x09, 0x8d, 0x44, 0x18, 0x4c, 0x39, 0x6a, 0x43, 0xed, 0x05, 0xbb,
	0xa1, 0x91, 0x63, 0xed, 0x5b, 0x5d, 0x9b, 0xa4, 0x06, 0xfe, 0x64, 0x41, 0xf3, 0x64, 0x1e, 0x4e,
	0x27, 0x84, 0xbe, 0x9b, 0x53, 0x2e, 0xd0, 0x91, 0x71, 0x4a, 0x05, 0x37, 0xfa, 0xdb, 0xbd, 0x38,
	0xe9, 0x69, 0x30, 0x31, 0x98, 0xbb, 0x50, 0xbf, 0xa0, 0x22, 0x98, 0x04, 0x22, 0x70, 0xd6, 0x54,
	0x7c, 0x53, 0xc6, 0xe7, 0x18, 0x29, 0xbc, 0xe8, 0x2f, 0xd8, 0x70, 0xd9, 0x2c, 0x66, 0x9c, 0x3a,
	0x15, 0x15, 0xd8, 0x50, 0xc4, 0x29, 0x44, 0x72, 0x9f, 0xd4, 0xe0, 0x85, 0xc2, 0xbd, 0xa6, 0xe3,
	0x1b, 0x36, 0x17, 0x4e, 0xb5, 0xd4, 0xa0, 0xc1, 0x44, 0x8f, 0x41, 0x7b, 0x50, 0x1d, 0xbc, 0xa7,
	0x63, 0xa7, 0xa6, 0x62, 0xeb, 0x32, 0x56, 0xda, 0x44, 0xa1, 0x08, 0x41, 0xf5, 0x9c, 0xd2, 0xd8,
	0x59, 0x57, 0xa5, 0xab, 0x6f, 0xfc, 0x7f, 0xa9, 0x5a, 0xfa, 0x9f, 0x07, 0x33, 0xaa, 0xd4, 0xdb,
	0x44, 0x7d, 0x23, 0x07, 0x36, 0x4e, 0xd9, 0x2c, 0x08, 0x23, 0xee, 0x54, 0xf6, 0x2b, 0x5d, 0x9b,
	0xe4, 0x26, 0x3e, 0x33, 0xe4, 0xa1, 0x3f, 0x00, 0x08, 0x8d, 0x19, 0x0f, 0x05, 0x4b, 0xee, 0xb2,
	0xee, 0x6a, 0x08, 0xea, 0x40, 0x9d, 0xd0, 0x45, 0xc8, 0x43, 0x16, 0x65, 0x09, 0x0a, 0x1b, 0x3f,
	0x2a, 0x1a, 0x82, 0x7a, 0x50, 0xf7, 0x69, 0xb2, 0x08, 0xc7, 0x54, 0x76, 0xbd, 0xd2, 0x6d, 0xf4,
	0x91, 0xd6, 0x9c, 0xcc, 0x45, 0x8a, 0x18, 0x7c, 0x6f, 0xc1, 0x96, 0xe9, 0x2c, 0xca, 0xb0, 0xb4,
	0x32, 0xda, 0x50, 0x3b, 0x9b, 0x05, 0x57, 0x79, 0x6d, 0xa9, 0x21, 0x8b, 0x7b, 0xc5, 0xa6, 0xf3,
	0x19, 0x2d, 0x8a, 0xcb, 0x4c, 0x19, 0x3f, 0x62, 0x89, 0xe0, 0x4e, 0x55, 0xe1, 0xa9, 0x81, 0xf6,
	0xa1, 0x31, 0x88, 0x16, 0x61, 0xc2, 0xa2, 0x19, 0x8d, 0x84, 0x53, 0x53, 0x3e, 0x1d, 0xc2, 0x8f,
	0xd3, 0x01, 0xa0, 0x3d, 0xb0, 0x5d, 0x16, 0x89, 0x20, 0x8c, 0x68, 0x92, 0x09, 0x29, 0x01, 0xc9,
	0xee, 0x0b, 0x1a, 0xf3, 0x8c, 0x21, 0x35, 0xf0, 0xdf, 0xb0, 0x99, 0xdd, 0x41, 0x1e, 0xb3, 0x88,
	0x2b, 0x79, 0x17, 0x94, 0x73, 0x29, 0x3b, 0xa5, 0xc8, 0x4d, 0xfc, 0xaf, 0x46, 0xff, 0xfd, 0xf5,
	0xe2, 0x0f, 0x96, 0x51, 0x80, 0x54, 0x29, 0xa3, 0x79, 0x1c, 0x8c, 0xf3, 0xe3, 0x25, 0xf0, 0x63,
	0xd7, 0x01, 0xfd, 0x03, 0x50, 0x48, 0x4a, 0xdb, 0xd6, 0xe8, 0x6f, 0xa6, 0xa3, 0xcb, 0x50, 0xa2,
	0x05, 0xe0, 0xd7, 0xb0, 0x7d, 0x4a, 0xf9, 0x38, 0x09, 0x2f, 0xe9, 0x0a, 0x6f, 0xee, 0x01, 0x89,
	0x78, 0x00, 0xad, 0x92, 0x39, 0xeb, 0xe4, 0x91, 0x39, 0x38, 0x8d, 0x5a, 0x83, 0xcd, 0x49, 0x3e,
	0x81, 0xc6, 0xb3, 0x90, 0x8b, 0x9f, 0x17, 0x87, 0x5d, 0x68, 0xa6, 0x0c, 0x99, 0x88, 0x63, 0x68,
	0x6a, 0x09, 0xf2, 0xeb, 0xbd, 0xa4, 0xc2, 0x08, 0xc2, 0x03, 0xa8, 0xf8, 0xfe, 0x50, 0xbe, 0xae,
	0xf3, 0x88, 0xdd, 0x46, 0x43, 0xc6, 0x45, 0x9a, 0xbd, 0x49, 0x34, 0x44, 0xfa, 0x47, 0x49, 0xb8,
	0x08, 0x04, 0x3d, 0xa7, 0x77, 0xaa, 0x1d, 0x4d, 0xa2, 0x21, 0xf8, 0x0d, 0x6c, 0xfa, 0xfe, 0xd0,
	0xa7, 0x2b, 0xd4, 0x83, 0x7e, 0x57, 0x52, 0xb2, 0xdd, 0xb6, 0x21, 0x43, 0x7d, 0x7f, 0x48, 0x24,
	0x86, 0x5b, 0xb0, 0x95, 0xd3, 0xa7, 0xc5, 0xe2, 0x13, 0x95, 0xd0, 0x5b, 0x25, 0x21, 0x3e, 0x50,
	0xac, 0x5e, 0xc9, 0x9a, 0x4b, 0xb0, 0x1e, 0x90, 0xf0, 0xd1, 0x02, 0xfb, 0x94, 0x8d, 0x6f, 0x68,
	0xe2, 0xbe, 0xbd, 0x4a, 0xb7, 0xcd, 0x55, 0xc8, 0x45, 0xb1, 0x8b, 0x0a, 0x5b, 0xfa, 0x5e, 0x72,
	0x9a, 0x44, 0xe5, 0xc5, 0x29, 0x6c, 0xe9, 0x1b, 0x05, 0x9c, 0xdf, 0xb2, 0x64, 0xa2, 0x76, 0xb3,
	0x4d, 0x0a, 0x5b, 0xbe, 0xa9, 0xc1, 0x2c, 0x08, 0xa7, 0x6a, 0x13, 0xdb, 0x24, 0x35, 0xe4, 0x15,
	0x7c, 0x3a, 0x17, 0xd7, 0x6a, 0xe5, 0xda, 0x44, 0x7d, 0xe3, 0x39, 0xec, 0x16, 0x52, 0x56, 0xeb,
	0xf9, 0x81, 0x56, 0x54, 0xd6, 0x79, 0xf5, 0xa8, 0x0a, 0x90, 0x94, 0x7e, 0xfc, 0x2b, 0xb4, 0xcd,
	0xb4, 0xd9, 0x2c, 0x86, 0x9a, 0x9c, 0xd5, 0x26, 0xe2, 0x6a, 0x19, 0xf4, 0xb9, 0x18, 0x32, 0xad,
	0x6f, 0xcb, 0xec, 0xdf, 0x57, 0x60, 0x6d, 0x44, 0xd0, 0x21, 0xd4, 0xd4, 0xba, 0x43, 0x2d, 0x19,
	0xa9, 0xff, 0xfa, 0x76, 0x76, 0x34, 0x24, 0xab, 0xe1, 0x97, 0x43, 0x0b, 0xfd, 0x07, 0xf5, 0xfc,
	0x65, 0xa3, 0x5d, 0x45, 0x6f, 0x6e, 0x90, 0x4e, 0xdb, 0x04, 0xf3, 0xa3, 0xe8, 0x00, 0xaa, 0xf2,
	0x25, 0x22, 0x55, 0x9c, 0xf6, 0xaa, 0x3b, 0xad, 0x12, 0x28, 0x82, 0x8f, 0x60, 0x3d, 0xbd, 0xcb,
	0x68, 0x27, 0xbb, 0x60, 0xe5, 0x08, 0x3b, 0x48, 0x87, 0xbe, 0x38, 0xe2, 0x69, 0x47, 0xbc, 0xe5,
	0x23, 0x9e, 0x71, 0xc4, 0x85, 0xa6, 0x3e, 0x2b, 0xf4, 0x9b, 0xd1, 0x2e, 0x2d, 0xa3, 0xb3, 0xec,
	0x78, 0x90, 0xc4, 0x5b, 0x22, 0xf1, 0xbe, 0x46, 0x62, 0x28, 0xb9, 0x5c, 0x57, 0xff, 0x95, 0x8e,
	0x3f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x0e, 0xc6, 0xf7, 0x37, 0x09, 0x00, 0x00,
}
