// Code generated by protoc-gen-go. DO NOT EDIT.
// source: m8s.proto

/*
Package m8s is a generated protocol buffer package.

It is generated from these files:
	m8s.proto

It has these top-level messages:
	Credentials
	CreateRequest
	Metadata
	Annotation
	BasicAuth
	GitCheckout
	Compose
	ComposeService
	Resource
	CreateResponse
	StepRequest
	StepResponse
	DescribeRequest
	DescribeResponse
	ListRequest
	Init
*/
package m8s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Credentials is used for authenicating with the PR service.
type Credentials struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Credentials) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// BuildRequest is used for submitting a new build.
type CreateRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Metadata    *Metadata    `protobuf:"bytes,2,opt,name=Metadata" json:"Metadata,omitempty"`
	Compose     *Compose     `protobuf:"bytes,3,opt,name=Compose" json:"Compose,omitempty"`
	GitCheckout *GitCheckout `protobuf:"bytes,4,opt,name=GitCheckout" json:"GitCheckout,omitempty"`
	Steps       []*Init      `protobuf:"bytes,5,rep,name=Steps" json:"Steps,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *CreateRequest) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreateRequest) GetCompose() *Compose {
	if m != nil {
		return m.Compose
	}
	return nil
}

func (m *CreateRequest) GetGitCheckout() *GitCheckout {
	if m != nil {
		return m.GitCheckout
	}
	return nil
}

func (m *CreateRequest) GetSteps() []*Init {
	if m != nil {
		return m.Steps
	}
	return nil
}

// Metadata is high level information about the build.
type Metadata struct {
	Name        string        `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Annotations []*Annotation `protobuf:"bytes,2,rep,name=Annotations" json:"Annotations,omitempty"`
	Domains     []string      `protobuf:"bytes,3,rep,name=Domains" json:"Domains,omitempty"`
	BasicAuth   *BasicAuth    `protobuf:"bytes,4,opt,name=BasicAuth" json:"BasicAuth,omitempty"`
	Retention   string        `protobuf:"bytes,5,opt,name=Retention" json:"Retention,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetAnnotations() []*Annotation {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Metadata) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Metadata) GetBasicAuth() *BasicAuth {
	if m != nil {
		return m.BasicAuth
	}
	return nil
}

func (m *Metadata) GetRetention() string {
	if m != nil {
		return m.Retention
	}
	return ""
}

// Annotation provides information about where the environment was triggered.
type Annotation struct {
	Name  string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *Annotation) Reset()                    { *m = Annotation{} }
func (m *Annotation) String() string            { return proto.CompactTextString(m) }
func (*Annotation) ProtoMessage()               {}
func (*Annotation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Annotation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Annotation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BasicAuth struct {
	User string `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=Pass" json:"Pass,omitempty"`
}

func (m *BasicAuth) Reset()                    { *m = BasicAuth{} }
func (m *BasicAuth) String() string            { return proto.CompactTextString(m) }
func (*BasicAuth) ProtoMessage()               {}
func (*BasicAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BasicAuth) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BasicAuth) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

// GitCheckout is the details required to checkout the codebase.
type GitCheckout struct {
	// The repository we are cloning:
	// * https://github.com/owner/repo.git
	// * https://<token>:x-oauth-basic@github.com/owner/repo.git
	Repository string `protobuf:"bytes,1,opt,name=Repository" json:"Repository,omitempty"`
	Revision   string `protobuf:"bytes,2,opt,name=Revision" json:"Revision,omitempty"`
}

func (m *GitCheckout) Reset()                    { *m = GitCheckout{} }
func (m *GitCheckout) String() string            { return proto.CompactTextString(m) }
func (*GitCheckout) ProtoMessage()               {}
func (*GitCheckout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GitCheckout) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *GitCheckout) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

// Compose is our environment data, marshalled from a docker compose file.
type Compose struct {
	Services []*ComposeService `protobuf:"bytes,1,rep,name=Services" json:"Services,omitempty"`
}

func (m *Compose) Reset()                    { *m = Compose{} }
func (m *Compose) String() string            { return proto.CompactTextString(m) }
func (*Compose) ProtoMessage()               {}
func (*Compose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Compose) GetServices() []*ComposeService {
	if m != nil {
		return m.Services
	}
	return nil
}

// ComposeService is a container defintion, which we will use to build a pod.
type ComposeService struct {
	Name         string    `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Image        string    `protobuf:"bytes,2,opt,name=Image" json:"Image,omitempty"`
	Limits       *Resource `protobuf:"bytes,3,opt,name=Limits" json:"Limits,omitempty"`
	Reservations *Resource `protobuf:"bytes,4,opt,name=Reservations" json:"Reservations,omitempty"`
	Volumes      []string  `protobuf:"bytes,5,rep,name=Volumes" json:"Volumes,omitempty"`
	Ports        []string  `protobuf:"bytes,6,rep,name=Ports" json:"Ports,omitempty"`
	Environment  []string  `protobuf:"bytes,7,rep,name=Environment" json:"Environment,omitempty"`
	Tmpfs        []string  `protobuf:"bytes,8,rep,name=Tmpfs" json:"Tmpfs,omitempty"`
	Capabilities []string  `protobuf:"bytes,9,rep,name=Capabilities" json:"Capabilities,omitempty"`
	Entrypoint   []string  `protobuf:"bytes,10,rep,name=Entrypoint" json:"Entrypoint,omitempty"`
}

func (m *ComposeService) Reset()                    { *m = ComposeService{} }
func (m *ComposeService) String() string            { return proto.CompactTextString(m) }
func (*ComposeService) ProtoMessage()               {}
func (*ComposeService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ComposeService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComposeService) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ComposeService) GetLimits() *Resource {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *ComposeService) GetReservations() *Resource {
	if m != nil {
		return m.Reservations
	}
	return nil
}

func (m *ComposeService) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ComposeService) GetPorts() []string {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ComposeService) GetEnvironment() []string {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *ComposeService) GetTmpfs() []string {
	if m != nil {
		return m.Tmpfs
	}
	return nil
}

func (m *ComposeService) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *ComposeService) GetEntrypoint() []string {
	if m != nil {
		return m.Entrypoint
	}
	return nil
}

// Resource is used for setting CPU and Memory of the build.
type Resource struct {
	CPU    string `protobuf:"bytes,1,opt,name=CPU" json:"CPU,omitempty"`
	Memory string `protobuf:"bytes,2,opt,name=Memory" json:"Memory,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Resource) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *Resource) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

// BuildResponse is a streamed response used for printing build output and status.
type CreateResponse struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// StepRequest is our command being send to the remote environment.
type StepRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Container   string       `protobuf:"bytes,3,opt,name=Container" json:"Container,omitempty"`
	Command     string       `protobuf:"bytes,4,opt,name=Command" json:"Command,omitempty"`
}

func (m *StepRequest) Reset()                    { *m = StepRequest{} }
func (m *StepRequest) String() string            { return proto.CompactTextString(m) }
func (*StepRequest) ProtoMessage()               {}
func (*StepRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StepRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *StepRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StepRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *StepRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

// StepResponse is a streamed response used to return output from the commands on the remove environment.
type StepResponse struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *StepResponse) Reset()                    { *m = StepResponse{} }
func (m *StepResponse) String() string            { return proto.CompactTextString(m) }
func (*StepResponse) ProtoMessage()               {}
func (*StepResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *StepResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// DescribeRequest asks for an Environment which has already been deployed.
type DescribeRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DescribeRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *DescribeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// DescribeResponse responds with an Environment.
type DescribeResponse struct {
	Namespace  string   `protobuf:"bytes,1,opt,name=Namespace" json:"Namespace,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Domains    []string `protobuf:"bytes,3,rep,name=Domains" json:"Domains,omitempty"`
	Containers []string `protobuf:"bytes,4,rep,name=Containers" json:"Containers,omitempty"`
	SSH        string   `protobuf:"bytes,5,opt,name=SSH" json:"SSH,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DescribeResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DescribeResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DescribeResponse) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *DescribeResponse) GetContainers() []string {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *DescribeResponse) GetSSH() string {
	if m != nil {
		return m.SSH
	}
	return ""
}

// DescribeRequest asks for all the Environments.
type ListRequest struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ListRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type Init struct {
	Name         string    `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Image        string    `protobuf:"bytes,2,opt,name=Image" json:"Image,omitempty"`
	Steps        []string  `protobuf:"bytes,3,rep,name=Steps" json:"Steps,omitempty"`
	Limits       *Resource `protobuf:"bytes,4,opt,name=Limits" json:"Limits,omitempty"`
	Reservations *Resource `protobuf:"bytes,5,opt,name=Reservations" json:"Reservations,omitempty"`
	Volumes      []string  `protobuf:"bytes,6,rep,name=Volumes" json:"Volumes,omitempty"`
}

func (m *Init) Reset()                    { *m = Init{} }
func (m *Init) String() string            { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()               {}
func (*Init) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Init) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Init) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Init) GetSteps() []string {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Init) GetLimits() *Resource {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *Init) GetReservations() *Resource {
	if m != nil {
		return m.Reservations
	}
	return nil
}

func (m *Init) GetVolumes() []string {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func init() {
	proto.RegisterType((*Credentials)(nil), "m8s.Credentials")
	proto.RegisterType((*CreateRequest)(nil), "m8s.CreateRequest")
	proto.RegisterType((*Metadata)(nil), "m8s.Metadata")
	proto.RegisterType((*Annotation)(nil), "m8s.Annotation")
	proto.RegisterType((*BasicAuth)(nil), "m8s.BasicAuth")
	proto.RegisterType((*GitCheckout)(nil), "m8s.GitCheckout")
	proto.RegisterType((*Compose)(nil), "m8s.Compose")
	proto.RegisterType((*ComposeService)(nil), "m8s.ComposeService")
	proto.RegisterType((*Resource)(nil), "m8s.Resource")
	proto.RegisterType((*CreateResponse)(nil), "m8s.CreateResponse")
	proto.RegisterType((*StepRequest)(nil), "m8s.StepRequest")
	proto.RegisterType((*StepResponse)(nil), "m8s.StepResponse")
	proto.RegisterType((*DescribeRequest)(nil), "m8s.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "m8s.DescribeResponse")
	proto.RegisterType((*ListRequest)(nil), "m8s.ListRequest")
	proto.RegisterType((*Init)(nil), "m8s.Init")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for M8S service

type M8SClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (M8S_CreateClient, error)
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (M8S_StepClient, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
}

type m8SClient struct {
	cc *grpc.ClientConn
}

func NewM8SClient(cc *grpc.ClientConn) M8SClient {
	return &m8SClient{cc}
}

func (c *m8SClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (M8S_CreateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_M8S_serviceDesc.Streams[0], c.cc, "/m8s.m8s/Create", opts...)
	if err != nil {
		return nil, err
	}
	x := &m8SCreateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type M8S_CreateClient interface {
	Recv() (*CreateResponse, error)
	grpc.ClientStream
}

type m8SCreateClient struct {
	grpc.ClientStream
}

func (x *m8SCreateClient) Recv() (*CreateResponse, error) {
	m := new(CreateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *m8SClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (M8S_StepClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_M8S_serviceDesc.Streams[1], c.cc, "/m8s.m8s/Step", opts...)
	if err != nil {
		return nil, err
	}
	x := &m8SStepClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type M8S_StepClient interface {
	Recv() (*StepResponse, error)
	grpc.ClientStream
}

type m8SStepClient struct {
	grpc.ClientStream
}

func (x *m8SStepClient) Recv() (*StepResponse, error) {
	m := new(StepResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *m8SClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/m8s.m8s/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for M8S service

type M8SServer interface {
	Create(*CreateRequest, M8S_CreateServer) error
	Step(*StepRequest, M8S_StepServer) error
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
}

func RegisterM8SServer(s *grpc.Server, srv M8SServer) {
	s.RegisterService(&_M8S_serviceDesc, srv)
}

func _M8S_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(M8SServer).Create(m, &m8SCreateServer{stream})
}

type M8S_CreateServer interface {
	Send(*CreateResponse) error
	grpc.ServerStream
}

type m8SCreateServer struct {
	grpc.ServerStream
}

func (x *m8SCreateServer) Send(m *CreateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _M8S_Step_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StepRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(M8SServer).Step(m, &m8SStepServer{stream})
}

type M8S_StepServer interface {
	Send(*StepResponse) error
	grpc.ServerStream
}

type m8SStepServer struct {
	grpc.ServerStream
}

func (x *m8SStepServer) Send(m *StepResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _M8S_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M8SServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m8s.m8s/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M8SServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M8S_serviceDesc = grpc.ServiceDesc{
	ServiceName: "m8s.m8s",
	HandlerType: (*M8SServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _M8S_Describe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Create",
			Handler:       _M8S_Create_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Step",
			Handler:       _M8S_Step_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "m8s.proto",
}

func init() { proto.RegisterFile("m8s.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0x2b, 0x35,
	0x10, 0x66, 0xf3, 0xd7, 0xec, 0x24, 0xfd, 0xc1, 0x0d, 0x68, 0x15, 0x55, 0x25, 0x32, 0x02, 0x05,
	0x84, 0x5a, 0x9a, 0x02, 0x2a, 0xdc, 0x95, 0x6d, 0x05, 0x95, 0x5a, 0x54, 0x39, 0xb4, 0x12, 0x97,
	0x6e, 0x3a, 0x50, 0xab, 0x59, 0x7b, 0x59, 0x3b, 0x91, 0xfa, 0x10, 0x48, 0x3c, 0x06, 0x6f, 0x80,
	0xc4, 0x15, 0xef, 0x73, 0x5e, 0xe2, 0xc8, 0xf6, 0x6e, 0x76, 0xb7, 0x6a, 0x75, 0x54, 0xf5, 0xdc,
	0x79, 0xbe, 0xf9, 0xd9, 0xcf, 0xf3, 0xcd, 0x78, 0x21, 0x4c, 0x8e, 0xf4, 0x5e, 0x9a, 0x29, 0xa3,
	0x48, 0x33, 0x39, 0xd2, 0xf4, 0x53, 0xe8, 0xc5, 0x19, 0xde, 0xa2, 0x34, 0x82, 0xcf, 0x35, 0x19,
	0x40, 0xfb, 0x57, 0x75, 0x8f, 0x32, 0x0a, 0x46, 0xc1, 0x38, 0x64, 0xde, 0xa0, 0x6f, 0x02, 0x58,
	0x8f, 0x33, 0xe4, 0x06, 0x19, 0xfe, 0xb9, 0x40, 0x6d, 0xc8, 0xa4, 0x96, 0xe6, 0xa2, 0x7b, 0x93,
	0xad, 0x3d, 0x5b, 0xbc, 0x82, 0xb3, 0x5a, 0xed, 0x2f, 0xa0, 0x7b, 0x81, 0x86, 0xdf, 0x72, 0xc3,
	0xa3, 0x86, 0x4b, 0x58, 0x77, 0x09, 0x05, 0xc8, 0x56, 0x6e, 0xf2, 0x39, 0xac, 0xc5, 0x2a, 0x49,
	0x95, 0xc6, 0xa8, 0xe9, 0x22, 0xfb, 0xbe, 0xb4, 0xc7, 0x58, 0xe1, 0xb4, 0x34, 0x7e, 0x12, 0x26,
	0xbe, 0xc3, 0xd9, 0xbd, 0x5a, 0x98, 0xa8, 0x55, 0xa1, 0x51, 0xc1, 0x59, 0x35, 0x88, 0x7c, 0x02,
	0xed, 0xa9, 0xc1, 0x54, 0x47, 0xed, 0x51, 0x73, 0xdc, 0x9b, 0x84, 0x2e, 0xfa, 0x4c, 0x0a, 0xc3,
	0x3c, 0x4e, 0xff, 0x0d, 0x4a, 0xa2, 0x84, 0x40, 0xeb, 0x17, 0x9e, 0x60, 0xde, 0x0f, 0x77, 0x26,
	0x07, 0xd0, 0x3b, 0x96, 0x52, 0x19, 0x6e, 0x84, 0x92, 0x3a, 0x6a, 0xb8, 0x3a, 0x9b, 0xae, 0x4e,
	0x89, 0xb3, 0x6a, 0x0c, 0x89, 0x60, 0xed, 0x44, 0x25, 0x5c, 0x48, 0x1d, 0x35, 0x47, 0xcd, 0x71,
	0xc8, 0x0a, 0x93, 0x7c, 0x05, 0xe1, 0x8f, 0x5c, 0x8b, 0xd9, 0xf1, 0xc2, 0xdc, 0xe5, 0x17, 0xd8,
	0x70, 0xa5, 0x56, 0x28, 0x2b, 0x03, 0xc8, 0x0e, 0x84, 0x0c, 0x8d, 0xed, 0xa8, 0x92, 0x51, 0xdb,
	0x71, 0x2a, 0x01, 0xfa, 0x1d, 0x40, 0xf9, 0xd1, 0x27, 0xa9, 0x0f, 0xa0, 0x7d, 0xcd, 0xe7, 0x0b,
	0x74, 0x02, 0x84, 0xcc, 0x1b, 0xf4, 0xb0, 0xc2, 0xc1, 0xa6, 0x5d, 0x69, 0xcc, 0x8a, 0x34, 0x7b,
	0xb6, 0xd8, 0x25, 0xd7, 0x3a, 0xcf, 0x72, 0x67, 0x7a, 0x56, 0xeb, 0x3d, 0xd9, 0x05, 0x60, 0x98,
	0x2a, 0x2d, 0x8c, 0xca, 0x1e, 0xf2, 0xe4, 0x0a, 0x42, 0x86, 0xd0, 0x65, 0xb8, 0x14, 0xda, 0x12,
	0xf7, 0x65, 0x56, 0x36, 0xfd, 0x61, 0x25, 0x37, 0xd9, 0x87, 0xee, 0x14, 0xb3, 0xa5, 0x98, 0xa1,
	0x9d, 0x2a, 0xdb, 0xd8, 0xed, 0xaa, 0xf4, 0xb9, 0x8f, 0xad, 0x82, 0xe8, 0xff, 0x0d, 0xd8, 0xa8,
	0x3b, 0x9f, 0xbb, 0xf8, 0x59, 0xc2, 0xff, 0x58, 0x5d, 0xdc, 0x19, 0xe4, 0x33, 0xe8, 0x9c, 0x8b,
	0x44, 0x18, 0x9d, 0x8f, 0x99, 0x1f, 0x48, 0x86, 0x5a, 0x2d, 0xb2, 0x19, 0xb2, 0xdc, 0x49, 0x0e,
	0xa0, 0xcf, 0x50, 0x63, 0xb6, 0xcc, 0x15, 0x6f, 0x3d, 0x15, 0x5c, 0x0b, 0xb1, 0x82, 0x5f, 0xab,
	0xf9, 0x22, 0x41, 0x3f, 0x67, 0x21, 0x2b, 0x4c, 0xcb, 0xe4, 0x52, 0x65, 0x46, 0x47, 0x1d, 0x87,
	0x7b, 0x83, 0x8c, 0xa0, 0x77, 0x2a, 0x97, 0x22, 0x53, 0x32, 0x41, 0x69, 0xa2, 0x35, 0xe7, 0xab,
	0x42, 0x6e, 0x35, 0x93, 0xf4, 0x77, 0x1d, 0x75, 0x7d, 0x9e, 0x33, 0x08, 0x85, 0x7e, 0xcc, 0x53,
	0x7e, 0x23, 0xe6, 0xc2, 0x08, 0xd4, 0x51, 0xe8, 0x9c, 0x35, 0xcc, 0x4a, 0x73, 0x2a, 0x4d, 0xf6,
	0x90, 0x2a, 0x21, 0x4d, 0x04, 0x2e, 0xa2, 0x82, 0xd0, 0x6f, 0xac, 0x34, 0xfe, 0x16, 0x64, 0x0b,
	0x9a, 0xf1, 0xe5, 0x55, 0xde, 0x3a, 0x7b, 0x24, 0x1f, 0x43, 0xe7, 0x02, 0x13, 0x2b, 0xaa, 0x6f,
	0x5d, 0x6e, 0xd1, 0x2f, 0x61, 0xa3, 0x78, 0x13, 0x74, 0xaa, 0xa4, 0x46, 0x7b, 0xe7, 0x0b, 0xd4,
	0xda, 0x76, 0xd9, 0xe7, 0x17, 0x26, 0xfd, 0x2b, 0x80, 0x9e, 0x5d, 0xae, 0xd7, 0x3c, 0x1f, 0x85,
	0xaa, 0x8d, 0x8a, 0xaa, 0x3b, 0x10, 0xc6, 0x4a, 0x1a, 0x2e, 0x24, 0x66, 0x4e, 0xc2, 0x90, 0x95,
	0x80, 0xe5, 0x13, 0xab, 0x24, 0xe1, 0xf2, 0xd6, 0x29, 0x16, 0xb2, 0xc2, 0xa4, 0x63, 0xe8, 0x7b,
	0x3a, 0xef, 0x64, 0xfe, 0x1b, 0x6c, 0x9e, 0xa0, 0x9e, 0x65, 0xe2, 0x06, 0xdf, 0x33, 0x79, 0xfa,
	0x77, 0x00, 0x5b, 0x65, 0xed, 0x9c, 0xc9, 0x0e, 0x84, 0xd6, 0xa9, 0x53, 0x3e, 0x2b, 0xb8, 0x94,
	0xc0, 0x93, 0x3d, 0x78, 0xfe, 0x69, 0xd9, 0x05, 0x58, 0x35, 0xc3, 0x0e, 0xad, 0xd3, 0xbd, 0x44,
	0xac, 0xd6, 0xd3, 0xe9, 0xcf, 0xf9, 0x33, 0x62, 0x8f, 0xf4, 0x18, 0x7a, 0xe7, 0x42, 0x9b, 0x57,
	0xdc, 0x94, 0xfe, 0x17, 0x40, 0xcb, 0xbe, 0xa6, 0x2f, 0xd8, 0xc2, 0x41, 0xf1, 0x22, 0x7b, 0xfe,
	0xde, 0xa8, 0xec, 0x66, 0xeb, 0x25, 0xbb, 0xd9, 0x7e, 0xd1, 0x6e, 0x76, 0x6a, 0xbb, 0x39, 0xf9,
	0x27, 0x00, 0xfb, 0x57, 0x24, 0xdf, 0x42, 0xc7, 0xcf, 0x36, 0x21, 0xc5, 0x6d, 0xcb, 0x9f, 0xdf,
	0x70, 0xbb, 0x86, 0x79, 0xe1, 0xe8, 0x07, 0x5f, 0x07, 0x64, 0x1f, 0x5a, 0x96, 0x3b, 0xf1, 0x2d,
	0xaa, 0x0c, 0xfc, 0xf0, 0xc3, 0x0a, 0x52, 0x49, 0xf8, 0x1e, 0xba, 0xc5, 0x04, 0x90, 0x81, 0x0b,
	0x79, 0x34, 0x6c, 0xc3, 0x8f, 0x1e, 0xa1, 0x45, 0xf2, 0x4d, 0xc7, 0xfd, 0xc4, 0x0f, 0xdf, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0x4b, 0x15, 0x55, 0xd1, 0x07, 0x00, 0x00,
}
